# Generated by Django 3.1.7 on 2021-03-11 04:03

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Driver',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('driver_license', models.CharField(default='FAKE980', max_length=30)),
                ('first_name', models.CharField(default='first', max_length=30)),
                ('last_name', models.CharField(default='last', max_length=30)),
                ('email', models.EmailField(default='fake@fake.com', max_length=30)),
                ('phone', models.PositiveIntegerField(default=6503339999)),
                ('password', models.CharField(max_length=30)),
                ('license_plate', models.CharField(blank=True, max_length=30, null=True)),
                ('route', models.TextField(blank=True, default='[]', null=True)),
                ('current_lat', models.FloatField(blank=True, default=38.2393, null=True)),
                ('current_long', models.FloatField(blank=True, default=-85.7598, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sunet', models.CharField(max_length=30)),
                ('first_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=30)),
                ('email', models.EmailField(max_length=30)),
                ('phone', models.PositiveIntegerField(default=6503339999)),
                ('password', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Ride',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current_address', models.CharField(max_length=150)),
                ('destination_address', models.CharField(max_length=150)),
                ('current_lat', models.FloatField(default=38.2393)),
                ('current_long', models.FloatField(default=-85.7598)),
                ('dest_lat', models.FloatField(default=37.4254)),
                ('dest_long', models.FloatField(default=-122.1629)),
                ('num_passengers', models.IntegerField(default=1)),
                ('safety_lvl', models.PositiveIntegerField(default=5)),
                ('priority', models.FloatField(default=50)),
                ('time_requested', models.DateTimeField(default=datetime.datetime.now, verbose_name='time requested')),
                ('picked_up', models.DateTimeField(default=datetime.datetime(1, 1, 1, 0, 0), null=True)),
                ('dropped_off', models.DateTimeField(default=datetime.datetime(1, 1, 1, 0, 0), null=True)),
                ('assigned', models.IntegerField(default=-1)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='dispatcher_controller.student')),
            ],
        ),
        migrations.CreateModel(
            name='location',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_picked_up', models.IntegerField(default=-1)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='dispatcher_controller.student')),
            ],
        ),
    ]
