# Generated by Django 3.1.7 on 2021-03-07 04:22

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ride',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current_location', models.CharField(max_length=30)),
                ('destination', models.CharField(max_length=30)),
                ('current_lat', models.FloatField(default=38.2393)),
                ('current_long', models.FloatField(default=-85.7598)),
                ('dest_lat', models.FloatField(default=37.4254)),
                ('dest_long', models.FloatField(default=-122.1629)),
                ('num_passengers', models.IntegerField(default=1)),
                ('safety_lvl', models.PositiveIntegerField(default=5)),
                ('priority', models.FloatField(default=50)),
                ('time_requested', models.DateTimeField(default=datetime.datetime.now, verbose_name='time requested')),
                ('picked_up', models.DateTimeField(default=datetime.datetime(1, 1, 1, 0, 0), null=True)),
                ('dropped_off', models.DateTimeField(default=datetime.datetime(1, 1, 1, 0, 0), null=True)),
                ('assigned', models.IntegerField(default=-1)),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_id', models.PositiveIntegerField(default=12345)),
                ('sunet', models.CharField(max_length=30)),
                ('first_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=30)),
                ('email', models.EmailField(max_length=30)),
                ('phone', models.PositiveIntegerField(default=6503339999)),
            ],
        ),
        migrations.CreateModel(
            name='Driver',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(default='first', max_length=30)),
                ('last_name', models.CharField(default='last', max_length=30)),
                ('license_plate', models.CharField(blank=True, max_length=30, null=True)),
                ('email', models.EmailField(default='fake@fake.com', max_length=30)),
                ('phone', models.PositiveIntegerField(default=6503339999)),
                ('passenger_list', models.TextField(default='[]')),
                ('current_lat', models.FloatField(default=38.2393)),
                ('current_long', models.FloatField(default=-85.7598)),
                ('route', models.TextField(default='[]')),
                ('student', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='dispatcher_controller.student')),
            ],
        ),
    ]
