# Generated by Django 3.1.5 on 2021-02-17 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dispatcher_controller', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ride',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='ride',
            name='student_id',
            field=models.PositiveIntegerField(default=6101297),
        ),
        migrations.AlterField(
            model_name='student',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
